### ISSUE TITLE
v1.6.2: TypeError: import_process.default.cwd is not a function

### ISSUE THREAD

**Issue by heiwen** [vercel/streamdown#246]
### Bug Description

I'm using the latest ai-sdk-elements example code for a chatbot in a React Router SPA (7.9.6) with React 19.1.1 using Chrome latest on MacOS.

https://ai-sdk.dev/elements/examples/chatbot

Everything works fine with streamdown 1.5.1. When upgrading to 1.6.2, I get the following error when sending a prompt to the chat endpoint:

```
import_process.default.cwd is not a function

TypeError: import_process.default.cwd is not a function
    at new Z (http://localhost:5173/node_modules/.vite/deps/chunk-NAXTZRU2.js?v=1db9ec66:25972:154)
    at pe (http://localhost:5173/node_modules/.vite/deps/chunk-NAXTZRU2.js?v=1db9ec66:26186:24)
    at s2.parse (http://localhost:5173/node_modules/.vite/deps/chunk-NAXTZRU2.js?v=1db9ec66:26079:13)
    at Oe (http://localhost:5173/node_modules/.vite/deps/chunk-NAXTZRU2.js?v=1db9ec66:26254:25)
    at Object.react_stack_bottom_frame (http://localhost:5173/node_modules/.vite/deps/react-dom_client.js?v=1db9ec66:18509:20)
    at renderWithHooks (http://localhost:5173/node_modules/.vite/deps/react-dom_client.js?v=1db9ec66:5654:24)
    at updateFunctionComponent (http://localhost:5173/node_modules/.vite/deps/react-dom_client.js?v=1db9ec66:7475:21)
    at beginWork (http://localhost:5173/node_modules/.vite/deps/react-dom_client.js?v=1db9ec66:8525:20)
    at runWithFiberInDEV (http://localhost:5173/node_modules/.vite/deps/react-dom_client.js?v=1db9ec66:997:72)
    at performUnitOfWork (http://localhost:5173/node_modules/.vite/deps/react-dom_client.js?v=1db9ec66:12561:98)
```

**Comment by haydenbleasel** [comment]
Hey @heiwen will look into it now, TY

**Comment by haydenbleasel** [comment]
Thanks for reporting this issue @heiwen and @RobPruzan!

We've identified the root cause: marked v16+ introduced dependencies on Node.js built-in modules (`path` and `process.cwd()`) which were causing issues in browser environments.

The fix is straightforward - we've updated the tsup configuration to explicitly target the browser platform, which ensures Node.js built-ins are properly shimmed for browser compatibility.

We've tested the fix locally and confirmed it resolves the issue. This will be included in the next patch release shortly.

**Comment by heiwen** [comment]
Awesome, thanks!

**Comment by haydenbleasel** [comment]
Okay it's out now, let me know if you're still facing any issues 🙏

**Comment by heiwen** [comment]
Tested and confirmed working. Thank you!
